server:
  port: 8080
  address: 127.0.0.1
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver



